package model;
// Generated 2016-11-13 14:49:11 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * HistoriaRezerwacji generated by hbm2java
 */
public class HistoriaRezerwacji implements java.io.Serializable {

	private HistoriaRezerwacjiId id;
	private Date dataOd;
	private Date dataDo;
	private boolean czyAnulowano;

	public HistoriaRezerwacji() {
	}

	public HistoriaRezerwacji(HistoriaRezerwacjiId id, Date dataOd, Date dataDo, boolean czyAnulowano) {
		this.id = id;
		this.dataOd = dataOd;
		this.dataDo = dataDo;
		this.czyAnulowano = czyAnulowano;
	}

	public HistoriaRezerwacjiId getId() {
		return this.id;
	}

	public void setId(HistoriaRezerwacjiId id) {
		this.id = id;
	}

	public Date getDataOd() {
		return this.dataOd;
	}

	public void setDataOd(Date dataOd) {
		this.dataOd = dataOd;
	}

	public Date getDataDo() {
		return this.dataDo;
	}

	public void setDataDo(Date dataDo) {
		this.dataDo = dataDo;
	}

	public boolean isCzyAnulowano() {
		return this.czyAnulowano;
	}

	public void setCzyAnulowano(boolean czyAnulowano) {
		this.czyAnulowano = czyAnulowano;
	}

}
