package model;
// Generated 2016-11-13 14:49:11 by Hibernate Tools 5.2.0.Beta1

/**
 * HistoriaRezerwacjiId generated by hbm2java
 */
public class HistoriaRezerwacjiId implements java.io.Serializable {

	private int id;
	private int uzytkownikId;
	private int pokojId;

	public HistoriaRezerwacjiId() {
	}

	public HistoriaRezerwacjiId(int id, int uzytkownikId, int pokojId) {
		this.id = id;
		this.uzytkownikId = uzytkownikId;
		this.pokojId = pokojId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getUzytkownikId() {
		return this.uzytkownikId;
	}

	public void setUzytkownikId(int uzytkownikId) {
		this.uzytkownikId = uzytkownikId;
	}

	public int getPokojId() {
		return this.pokojId;
	}

	public void setPokojId(int pokojId) {
		this.pokojId = pokojId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistoriaRezerwacjiId))
			return false;
		HistoriaRezerwacjiId castOther = (HistoriaRezerwacjiId) other;

		return (this.getId() == castOther.getId()) && (this.getUzytkownikId() == castOther.getUzytkownikId())
				&& (this.getPokojId() == castOther.getPokojId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getUzytkownikId();
		result = 37 * result + this.getPokojId();
		return result;
	}

}
