package model;
// Generated 2016-11-13 14:49:11 by Hibernate Tools 5.2.0.Beta1

/**
 * Przypomnienia generated by hbm2java
 */
public class Przypomnienia implements java.io.Serializable {

	private PrzypomnieniaId id;
	private boolean czyZobaczone;

	public Przypomnienia() {
	}

	public Przypomnienia(PrzypomnieniaId id, boolean czyZobaczone) {
		this.id = id;
		this.czyZobaczone = czyZobaczone;
	}

	public PrzypomnieniaId getId() {
		return this.id;
	}

	public void setId(PrzypomnieniaId id) {
		this.id = id;
	}

	public boolean isCzyZobaczone() {
		return this.czyZobaczone;
	}

	public void setCzyZobaczone(boolean czyZobaczone) {
		this.czyZobaczone = czyZobaczone;
	}

}
