package model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2016-11-13 14:49:11 by Hibernate Tools 5.2.0.Beta1

/**
 * Rola generated by hbm2java
 */

@Entity
@Table(name = "Rola")
public class Rola implements java.io.Serializable {

	@Id
	private Integer id;
	private String nazwa;

	public Rola() {
	}

	public Rola(String nazwa) {
		this.nazwa = nazwa;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

}
