package model;
// Generated 2016-11-13 14:49:11 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Uzytkownik generated by hbm2java
 */
@Entity
@Table(name = "Uzytkownik")
public class Uzytkownik implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1970451232521873149L;

	@Id
	private UzytkownikId id;
	private String login;
	private String haslo;
	
	
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Uzytkownik() {
	}

	public Uzytkownik(UzytkownikId id, String login, String haslo) {
		this.id = id;
		this.login = login;
		this.haslo = haslo;
	}

	public UzytkownikId getId() {
		return this.id;
	}

	public void setId(UzytkownikId id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getHaslo() {
		return this.haslo;
	}

	public void setHaslo(String haslo) {
		this.haslo = haslo;
	}

}
