package model;
// Generated 2016-11-13 14:49:11 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * UzytkownikId generated by hbm2java
 */
@Entity
public class UzytkownikId implements java.io.Serializable {

	@Id
	@GeneratedValue
	private int id;
	private int rolaId;

	public UzytkownikId() {
	}

	public UzytkownikId(int id, int rolaId) {
		this.id = id;
		this.rolaId = rolaId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getRolaId() {
		return this.rolaId;
	}

	public void setRolaId(int rolaId) {
		this.rolaId = rolaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UzytkownikId))
			return false;
		UzytkownikId castOther = (UzytkownikId) other;

		return (this.getId() == castOther.getId()) && (this.getRolaId() == castOther.getRolaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getRolaId();
		return result;
	}

}
